import axios from "axios";

const api = axios.create({
  baseURL: "/api",
  headers: {
    "Content-Type": "application/json",
  },
});

api.interceptors.request.use(
  (config) => {
    const token = sessionStorage.getItem("token");
    if (token) {
      config.headers["Authorization"] = `Bearer ${token}`;
    }
    return config;
  },
  (error) => Promise.reject(error)
);   

export const registerAPI = async (values) => {
  const userData = {
      id: null, // Assuming ID is generated by the server
      fullName: values.fullName,
      phone: values.phone,
      gender: values.gender,
      birthDate: values.birthDate ? values.birthDate.format("YYYY-MM-DD") : null,
      address: values.address,
      email: values.email,
      userName: values.username,
      password: values.password,
      roleId: 4, 
   };
  return api.post("/auth/register", userData);
};

export const loginAPI = async (values) => {
  const userData = {
    usernameOrEmail: values.username,
    password: values.password,
  }
  return api.post("/auth/login", userData);
};

export const getUserProfile = async () => {
  return api.get("/user/profile");
}
